language: ruby
sudo: false
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
